export const pokemonTypes = [
  {
    name: "노말",
    en: "normal",
    zh: "一般",
    color: "#A8A77A",
    colorName: "gray",
  },
  { name: "불꽃", en: "fire", zh: "火", color: "#EE8130", colorName: "red" },
  { name: "물", en: "water", zh: "水", color: "#6390F0", colorName: "blue" },
  {
    name: "전기",
    en: "electric",
    zh: "电",
    color: "#F7D02C",
    colorName: "yellow",
  },
  { name: "풀", en: "grass", zh: "草", color: "#7AC74C", colorName: "green" },
  {
    name: "얼음",
    en: "ice",
    zh: "冰",
    color: "#96D9D6",
    colorName: "lightblue",
  },
  {
    name: "격투",
    en: "fighting",
    zh: "格斗",
    color: "#C22E28",
    colorName: "red",
  },
  { name: "독", en: "poison", zh: "毒", color: "#A33EA1", colorName: "purple" },
  {
    name: "땅",
    en: "ground",
    zh: "地面",
    color: "#E2BF65",
    colorName: "brown",
  },
  {
    name: "비행",
    en: "flying",
    zh: "飞行",
    color: "#A98FF3",
    colorName: "lightpurple",
  },
  {
    name: "에스퍼",
    en: "psychic",
    zh: "超能力",
    color: "#F95587",
    colorName: "pink",
  },
  { name: "벌레", en: "bug", zh: "虫", color: "#A6B91A", colorName: "green" },
  {
    name: "바위",
    en: "rock",
    zh: "岩石",
    color: "#B6A136",
    colorName: "brown",
  },
  {
    name: "고스트",
    en: "ghost",
    zh: "幽灵",
    color: "#735797",
    colorName: "purple",
  },
  {
    name: "드래곤",
    en: "dragon",
    zh: "龙",
    color: "#6F35FC",
    colorName: "blue",
  },
  { name: "악", en: "dark", zh: "恶", color: "#705746", colorName: "brown" },
  { name: "강철", en: "steel", zh: "钢", color: "#B7B7CE", colorName: "gray" },
  {
    name: "페어리",
    en: "fairy",
    zh: "妖精",
    color: "#D685AD",
    colorName: "pink",
  },
];

export const typeStyleMap: Record<string, { bg: string; text: string }> = {
  normal: { bg: "bg-gray-400", text: "text-black" },
  fire: { bg: "bg-red-500", text: "text-white" },
  water: { bg: "bg-blue-500", text: "text-white" },
  electric: { bg: "bg-yellow-400", text: "text-black" },
  grass: { bg: "bg-green-500", text: "text-black" },
  ice: { bg: "bg-cyan-300", text: "text-black" },
  fighting: { bg: "bg-red-700", text: "text-white" },
  poison: { bg: "bg-purple-500", text: "text-white" },
  ground: { bg: "bg-amber-600", text: "text-black" },
  flying: { bg: "bg-indigo-400", text: "text-white" },
  psychic: { bg: "bg-pink-500", text: "text-white" },
  bug: { bg: "bg-lime-500", text: "text-black" },
  rock: { bg: "bg-stone-500", text: "text-white" },
  ghost: { bg: "bg-violet-600", text: "text-white" },
  dragon: { bg: "bg-blue-700", text: "text-white" },
  dark: { bg: "bg-neutral-700", text: "text-white" },
  steel: { bg: "bg-gray-500", text: "text-black" },
  fairy: { bg: "bg-pink-400", text: "text-black" },
};
